### ISSUE TITLE
Weird stub behaviour on RBX and JRuby

### ISSUE THREAD

**Issue by pawelpacana** [psyho/bogus#45]
I've noticed that stubs behave differenty on Rubinius and JRuby than on MRI. Have a look on following example: https://gist.github.com/pawelpacana/6973039

I've observed this behaviour first on https://github.com/pawelpacana/citrus-core/blob/master/spec/citrus/core/test_runner_spec.rb#L24

**Comment by psyho** [comment]
I included the test case for this bug in our test suite. As far as I can tell, in the latest release (0.1.6) this should be fixed.
