### ISSUE TITLE
Argument requirements on .new

### ISSUE THREAD

**Issue by terrellt** [psyho/bogus#65]
Given
```ruby
class TestClass
  def initialize(foo, bar)
  end
end
```

I would expect
```ruby
stub(TestClass).new(1) { fake(:test_class) }
```
to throw an error, because TestClass can't instantiate with only one argument. It doesn't. Is this because it's sidestepping #initialize, where the arguments are actually defined?

**Comment by terrellt** [comment]
@psyho https://github.com/terrellt/bogus/commit/2cd401328e39f3b7372faee5220c81ca26c7000c I think this covers it.

**Comment by psyho** [comment]
Thanks for catching this issue.

BTW. You don't need to call `object.allocate.method()`, you can also use `object.instance_method()`.

**Comment by terrellt** [comment]
Ah, thanks. Would you like me to change that bit and send a PR, or would you like to do the commit?

**Comment by psyho** [comment]
I cherry-picked your commit and made some cosmetic changes. Thank you for your help.

**Comment by terrellt** [comment]
Very nice, thank you for getting it in.
